FROM node:16.17.0
WORKDIR /usr
COPY package.json ./
COPY tsconfig.json ./
RUN ls -a
RUN npm install
EXPOSE 3003
CMD ["npm","run","dev"]

# FROM node:12.17.0-alpine
# WORKDIR /usr
# COPY package.json ./
# COPY tsconfig.json ./
# RUN ls -a
# RUN npm install
# # RUN npm run build

# FROM node:12.17.0-alpine
# WORKDIR /usr
# COPY package.json ./
# RUN npm install --only=production
# COPY --from=0 /usr/build .
# RUN npm install pm2 -g
# EXPOSE 80
# CMD ["pm2-runtime","app.js"]



# FROM node:alpine As development

# WORKDIR /usr

# COPY package.json ./

# RUN npm install

# COPY . .

# RUN npm run build

# FROM node:alpine as production

# ARG NODE_ENV=production
# ENV NODE_ENV=${NODE_ENV}

# WORKDIR /usr

# COPY package.json ./

# RUN npm install --only=production

# COPY . .

# COPY --from=development /usr/build ./build

# CMD ["node", "build/app"]