FROM node:16.17.0-alpine
WORKDIR /usr
COPY package.json ./
COPY tsconfig.json ./
COPY . ./
RUN ls -a
RUN npm install

FROM node:16.17.0-alpine
# WORKDIR /usr
COPY package.json ./
RUN npm install --only=production
COPY --from=0 /usr .
EXPOSE 80
RUN npm run build
CMD ["node","dist/app.js"]