version: '3.7'

services:
    app:
        container_name: app
        restart: always
        build: .
        env_file: .env
        environment:
            - PORT=${PORT}
            - NODE_ENV=${NODE_ENV}
            - DBURI=${DBURI}
            - PASSWORD_SALT=${PASSWORD_SALT}
            - EMAIL_NAME_FROM=${EMAIL_NAME_FROM}
            - EMAIL_FROM=${EMAIL_FROM}
            - JWT_SECRET=${JWT_SECRET}
            - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
            - EMAIL_PASSWORD=${EMAIL_PASSWORD}
            - EMAIL_USERNAME=${EMAIL_USERNAME}
            - EMAIL_SERVICE=${EMAIL_SERVICE}
            - EMAIL_PORT=${EMAIL_PORT}
        expose:
            - ${PORT}
        depends_on:
            - mongodb

    mongodb:
        container_name: mongodb
        image: mongo
        restart: always
        ports:
            - 27017:27017