export enum LaundryTypeEnum {
    WASH_ONLY = 'WASH ONLY',
    WASH_AND_STARCH = 'WASH AND STARCH',
    WASH_FOLD_AND_IRON = 'WASH, FOLD AND IRON',
    WASH_AND_FOLD = 'WASH AND FOLD',
    IRON_ONLY = 'IRON ONLY',
}
